### ISSUE TITLE
Future<String> getByKey(String key)  - why return a String?

### ISSUE THREAD

**Issue by lymp** [sethladd/lawndart#27]
Hi,
Shouldn't the declaration be
Future**<'Map>** getByKey(String key);
not
Future**<'String>** getByKey(String key);
?
I am successfully using it to return a Map future, but of course the Dart editor shows a warning.

Steve Lympany

**Comment by sethladd** [comment]
Hi, thanks for checking out lawndart.

Lawndart only supports String->String key/value pairs. If you are storing another type of object, it's at your own risk. :)

I'm surprised it's working to return a Map.

Closing for now, but if I misunderstood your issue, please let me know.
